project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    left:
      - href: index.qmd
        text: Home
<<<<<<< HEAD
      - href: about.qmd 
        text: About
      - href: projects.qmd
        text: project
      - href: lab.qmd
        text: Labs
      - href: presentation.qmd
        text: presentation
              
=======
      - about.qmd
        text: About
>>>>>>> a095fbca72eb20419d71cf7a3823bff2c4bcf403

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true

editor: visual



